name: UniqueSdk

############
# Options
############

options:
  minimumXcodeGenVersion: 2.10
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget: 
    iOS: "13.0"


############
# Packages
############



############
# Targets
############

targets:
  UniqueSdk:
    type: framework
    platform: iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.UniqueSdk.UniqueSdk"
    scheme:
      gatherCoverageData: true
    info:
      path: UniqueSdk/Supporting Files/Info.plist
    sources:
      - UniqueSdk
      - path: UniqueSdk/Supporting Files/UniqueSdk.h
        buildPhase: headers
        headerVisibility: public
    
  UniqueSDKDemo:
    type: application
    platform: iOS
 
    # devices: [iPhone, iPad]
    settings:
      base:
        SWIFT_VERSION: 5.5.2
        # TARGETED_DEVICE_FAMILY: 1
        CODE_SIGN_STYLE: "Manual"
        ENABLE_BITCODE: false
        DEVELOPMENT_TEAM: 3382SF795H
        CURRENT_PROJECT_VERSION: 1
        VERSIONING_SYSTEM: "apple-generic"
        USE_SWIFT_RESPONSE_FILE: true
        OTHER_LDFLAGS: [-ObjC]

    info:
      path: UniqueSDKDemo/Supporting Files/Info.plist
      properties:
        UILaunchStoryboardName: "Launch Screen"
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        NSLocationWhenInUseUsageDescription: "Приложение позволит определить ближайший к Вам город с доступной недвижимостью"
        NSUserTrackingUsageDescription: "Идентификатор будет использоваться для сбора данных о сбоях и действиях в приложении для улучшения функциональности и взаимодействия с пользователем"
        CFBundleDisplayName: "Самолет Плюс"
        CFBundleShortVersionString: "1.2.0"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIRequiresFullScreen: true
        CFBundleDevelopmentRegion: "ru"
        CFBundleLocalizations: ["ru"]
        ITSAppUsesNonExemptEncryption: false
        UIUserInterfaceStyle: "Light"
#    postCompileScripts:
#      - path: swiftlint.sh
#        name: SwiftLint
    sources:
      - path: UniqueSDKDemo
      - path: UniqueSDKDemo/Assets.xcassets
    dependencies:
      - target: UniqueSdk

targetTemplates:
  Framework:
    type: framework
    platform: iOS
    deploymentTarget: 13.0
    settings:
      base:
        MARKETING_VERSION: 1.0
        SWIFT_VERSION: 5.0.0
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTS_MACCATALYST: NO
